development:
  adapter: postgresql
  
  encoding: unicode

  pool: 5
  
  template: template0
  
  database: amazon_development

  username: amazon

  password: amazon

  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  port: 5432
  
test:
  adapter: postgresql
  
  encoding: unicode

  pool: 5
  
  template: template0
  
  database: amazon_test
  
  username: amazon
   
  password: amazon
  
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  port: 5432

production:
  adapter: postgresql
  
  encoding: unicode

  pool: 5
  
  template: template0